# Generated by Django 3.1.3 on 2020-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201210_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='document',
            table='Documents',
        ),
    ]
