# Generated by Django 3.1.3 on 2021-01-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
