# Generated by Django 3.1.3 on 2020-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_document_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', verbose_name='Документ'),
        ),
    ]
